const Books = [
  {
    name: 'Genesis',
    name_id: 'Kejadian',
    total: 50,
    value: 'Gen',
    value_id: 'Kej',
    type: 'old',
    playlistId: '41351366',
  },
  {
    name: 'Exodus',
    name_id: 'Keluaran',
    total: 40,
    value: 'Exo',
    value_id: 'Kel',
    type: 'old',
    playlistId: '42042217',
  },
  {
    name: 'Leviticus',
    name_id: 'Imamat',
    total: 27,
    value: 'Lev',
    value_id: 'Ima',
    type: 'old',
    playlistId: '42692804',
  },
  {
    name: 'Numbers',
    name_id: 'Bilangan',
    total: 36,
    value: 'Num',
    value_id: 'Bil',
    type: 'old',
    playlistId: '42797308',
  },
  {
    name: 'Deuteronomy',
    name_id: 'Ulangan',
    total: 34,
    value: 'Deu',
    value_id: 'Ula',
    type: 'old',
    playlistId: '42803709',
  },
  {
    name: 'Joshua',
    name_id: 'Yosua',
    total: 24,
    value: 'Jos',
    value_id: 'Yos',
    type: 'old',
    playlistId: '43555028',
  },
  {
    name: 'Judges',
    name_id: 'Hakim-Hakim',
    total: 21,
    value: 'Jdg',
    value_id: 'Hak',
    type: 'old',
    playlistId: '43919544',
  },
  {
    name: 'Ruth',
    name_id: 'Rut',
    total: 4,
    value: 'Rth',
    value_id: 'Rut',
    type: 'old',
    playlistId: '45974061',
  },
  {
    name: '1 Samuel',
    name_id: '1 Samuel',
    total: 31,
    value: '1Sa',
    value_id: '1Sa',
    type: 'old',
    playlistId: '45974662',
  },
  {
    name: '2 Samuel',
    name_id: '2 Samuel',
    total: 24,
    value: '2Sa',
    value_id: '2Sa',
    type: 'old',
    playlistId: '51029551',
  },
  {
    name: '1 Kings',
    name_id: '1 Raja-Raja',
    total: 22,
    value: '1Ki',
    value_id: '1Ra',
    type: 'old',
    playlistId: '55122432',
  },
  {
    name: '2 Kings',
    name_id: '2 Raja-Raja',
    total: 25,
    value: '2Ki',
    value_id: '2Ra',
    type: 'old',
    playlistId: '78536204',
  },
  {
    name: '1 Chronicles',
    name_id: '1 Tawarikh',
    total: 29,
    value: '1Ch',
    value_id: '1Ta',
    type: 'old',
    playlistId: '137787467',
  },
  {
    name: '2 Chronicles',
    name_id: '2 Tawarikh',
    total: 36,
    value: '2Ch',
    value_id: '2Ta',
    type: 'old',
    playlistId: '201343776',
  },
  {
    name: 'Ezra',
    name_id: 'Ezra',
    total: 10,
    value: 'Ezr',
    value_id: 'Ezr',
    type: 'old',
    playlistId: '201347117',
  },
  {
    name: 'Nehemiah',
    name_id: 'Nehemia',
    total: 13,
    value: 'Neh',
    value_id: 'Neh',
    type: 'old',
    playlistId: '201349877',
  },
  {
    name: 'Esther',
    name_id: 'Ester',
    total: 10,
    value: 'Est',
    value_id: 'Est',
    type: 'old',
    playlistId: '137767348',
  },
  {
    name: 'Job',
    name_id: 'Ayub',
    total: 42,
    value: 'Job',
    value_id: 'Ayb',
    type: 'old',
    playlistId: '201353404',
  },
  {
    name: 'Psalms',
    name_id: 'Mazmur',
    total: 150,
    value: 'Ps',
    value_id: 'Mzm',
    type: 'old',
    playlistId: '197706713',
  },
  {
    name: 'Proverbs',
    name_id: 'Amsal',
    total: 31,
    value: 'Pro',
    value_id: 'Ams',
    type: 'old',
    playlistId: '178411852',
  },
  {
    name: 'Ecclesiastes',
    name_id: 'Pengkhotbah',
    total: 12,
    value: 'Ecc',
    value_id: 'Pkh',
    type: 'old',
    playlistId: '196745587',
  },
  {
    name: 'Song of Solomon',
    name_id: 'Kidung Agung',
    total: 8,
    value: 'Son',
    value_id: 'Kid',
    type: 'old',
    playlistId: '196746467',
  },
  {
    name: 'Isaiah',
    name_id: 'Yesaya',
    total: 66,
    value: 'Isa',
    value_id: 'Yes',
    type: 'old',
    playlistId: '197060630',
  },
  {
    name: 'Jeremiah',
    name_id: 'Yeremia',
    total: 52,
    value: 'Jer',
    value_id: 'Yer',
    type: 'old',
    playlistId: '197076268',
  },
  {
    name: 'Lamentations',
    name_id: 'Ratapan',
    total: 5,
    value: 'Lam',
    value_id: 'Rat',
    type: 'old',
    playlistId: '196753226',
  },
  {
    name: 'Ezekiel',
    name_id: 'Yehezkiel',
    total: 48,
    value: 'Eze',
    value_id: 'Yeh',
    type: 'old',
    playlistId: '197094631',
  },
  {
    name: 'Daniel',
    name_id: 'Daniel',
    total: 12,
    value: 'Dan',
    value_id: 'Dan',
    type: 'old',
    playlistId: '197373044',
  },
  {
    name: 'Hosea',
    name_id: 'Hosea',
    total: 14,
    value: 'Hos',
    value_id: 'Hos',
    type: 'old',
    playlistId: '197373735',
  },
  {
    name: 'Joel',
    name_id: 'Yoel',
    total: 3,
    value: 'Joe',
    value_id: 'Yoe',
    type: 'old',
    playlistId: '196753456',
  },
  {
    name: 'Amos',
    name_id: 'Amos',
    total: 9,
    value: 'Amo',
    value_id: 'Amo',
    type: 'old',
    playlistId: '197376770',
  },
  {
    name: 'Obadiah',
    name_id: 'Obaja',
    total: 1,
    value: 'Oba',
    value_id: 'Oba',
    type: 'old',
    playlistId: '196753357',
  },
  {
    name: 'Jonah',
    name_id: 'Yunus',
    total: 4,
    value: 'Jon',
    value_id: 'Yun',
    type: 'old',
    playlistId: '196753344',
  },
  {
    name: 'Micah',
    name_id: 'Mikha',
    total: 7,
    value: 'Mic',
    value_id: 'Mik',
    type: 'old',
    playlistId: '197040972',
  },
  {
    name: 'Nahum',
    name_id: 'Nahum',
    total: 3,
    value: 'Nah',
    value_id: 'Nah',
    type: 'old',
    playlistId: '197041347',
  },
  {
    name: 'Habakkuk',
    name_id: 'Habakuk',
    total: 3,
    value: 'Hab',
    value_id: 'Hab',
    type: 'old',
    playlistId: '197041577',
  },
  {
    name: 'Zephaniah',
    name_id: 'Zefanya',
    total: 3,
    value: 'Zep',
    value_id: 'Zef',
    type: 'old',
    playlistId: '197042184',
  },
  {
    name: 'Haggai',
    name_id: 'Hagai',
    total: 2,
    value: 'Hag',
    value_id: 'Hag',
    type: 'old',
    playlistId: '197042334',
  },
  {
    name: 'Zechariah',
    name_id: 'Zakharia',
    total: 14,
    value: 'Zec',
    value_id: 'Zak',
    type: 'old',
    playlistId: '197379269',
  },
  {
    name: 'Malachi',
    name_id: 'Maleakhi',
    total: 4,
    value: 'Mal',
    value_id: 'Mal',
    type: 'old',
    playlistId: '197039876',
  },
  {
    name: 'Matthew',
    name_id: 'Matius',
    total: 28,
    value: 'Mat',
    value_id: 'Mat',
    type: 'new',
    playlistId: '41313813',
  },
  {
    name: 'Mark',
    name_id: 'Markus',
    total: 16,
    value: 'Mrk',
    value_id: 'Mrk',
    type: 'new',
    playlistId: '41484297',
  },
  {
    name: 'Luke',
    name_id: 'Lukas',
    total: 24,
    value: 'Luk',
    value_id: 'Luk',
    type: 'new',
    playlistId: '41609263',
  },
  {
    name: 'John',
    name_id: 'Yohanes',
    total: 21,
    value: 'Joh',
    value_id: 'Yoh',
    type: 'new',
    playlistId: '41942175',
  },
  {
    name: 'Acts',
    name_id: 'Kisah Para Rasul',
    total: 28,
    value: 'Act',
    value_id: 'Kis',
    type: 'new',
    playlistId: '41943858',
  },
  {
    name: 'Romans',
    name_id: 'Roma',
    total: 16,
    value: 'Rom',
    value_id: 'Rom',
    type: 'new',
    playlistId: '41330668',
  },
  {
    name: '1 Corinthians',
    name_id: '1 Korintus',
    total: 16,
    value: '1Co',
    value_id: '1Ko',
    type: 'new',
    playlistId: '55791463',
  },
  {
    name: '2 Corinthians',
    name_id: '2 Korintus',
    total: 13,
    value: '2Co',
    value_id: '2Ko',
    type: 'new',
    playlistId: '55795693',
  },
  {
    name: 'Galatians',
    name_id: 'Galatia',
    total: 6,
    value: 'Gal',
    value_id: 'Gal',
    type: 'new',
    playlistId: '55807345',
  },
  {
    name: 'Ephesians',
    name_id: 'Efesus',
    total: 6,
    value: 'Eph',
    value_id: 'Efe',
    type: 'new',
    playlistId: '55811722',
  },
  {
    name: 'Philippians',
    name_id: 'Filipi',
    total: 4,
    value: 'Php',
    value_id: 'Fil',
    type: 'new',
    playlistId: '55814283',
  },
  {
    name: 'Colossians',
    name_id: 'Kolose',
    total: 4,
    value: 'Col',
    value_id: 'Kol',
    type: 'new',
    playlistId: '55816339',
  },
  {
    name: '1 Thessalonians',
    name_id: '1 Tesalonika',
    total: 5,
    value: '1Te',
    value_id: '1Te',
    type: 'new',
    playlistId: '62478131',
  },
  {
    name: '2 Thessalonians',
    name_id: '2 Tesalonika',
    total: 3,
    value: '2Te',
    value_id: '2Te',
    type: 'new',
    playlistId: '69620942',
  },
  {
    name: '1 Timothy',
    name_id: '1 Timotius',
    total: 6,
    value: '1Ti',
    value_id: '1Ti',
    type: 'new',
    playlistId: '69622338',
  },
  {
    name: '2 Timothy',
    name_id: '2 Timotius',
    total: 4,
    value: '2Ti',
    value_id: '2Ti',
    type: 'new',
    playlistId: '69623740',
  },
  {
    name: 'Titus',
    name_id: 'Titus',
    total: 3,
    value: 'Tit',
    value_id: 'Tit',
    type: 'new',
    playlistId: '70166321',
  },
  {
    name: 'Philemon',
    name_id: 'Filemon',
    total: 1,
    value: 'Phm',
    value_id: 'Flm',
    type: 'new',
    playlistId: '70167696',
  },
  {
    name: 'Hebrews',
    name_id: 'Ibrani',
    total: 13,
    value: 'Heb',
    value_id: 'Ibr',
    type: 'new',
    playlistId: '70169807',
  },
  {
    name: 'James',
    name_id: 'Yakobus',
    total: 5,
    value: 'Jas',
    value_id: 'Yak',
    type: 'new',
    playlistId: '70172454',
  },
  {
    name: '1 Peter',
    name_id: '1 Petrus',
    total: 5,
    value: '1Pe',
    value_id: '1Pe',
    type: 'new',
    playlistId: '70422586',
  },
  {
    name: '2 Peter',
    name_id: '2 Petrus',
    total: 3,
    value: '2Pe',
    value_id: '2Pe',
    type: 'new',
    playlistId: '70424815',
  },
  {
    name: '1 John',
    name_id: '1 Yohanes',
    total: 5,
    value: '1Jo',
    value_id: '1Yo',
    type: 'new',
    playlistId: '71800813',
  },
  {
    name: '2 John',
    name_id: '2 Yohanes',
    total: 1,
    value: '2Jo',
    value_id: '2Yo',
    type: 'new',
    playlistId: '71811294',
  },
  {
    name: '3 John',
    name_id: '3 Yohanes',
    total: 1,
    value: '3Jo',
    value_id: '3Yo',
    type: 'new',
    playlistId: '71811330',
  },
  {
    name: 'Jude',
    name_id: 'Yudas',
    total: 1,
    value: 'Jud',
    value_id: 'Yud',
    type: 'new',
    playlistId: '72028672',
  },
  {
    name: 'Revelation',
    name_id: 'Wahyu',
    total: 22,
    value: 'Rev',
    value_id: 'Wah',
    type: 'new',
    playlistId: '72033886',
  },
];

export default Books;
